spring:
  application:
    name: servicea

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://alfecjo:acfa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health

# Requisição para servicea direto - com autenticação:
#curl -u alfecjo:acfa -X GET http://host.docker.internal:8081/helloWorld

# Requisição para servicea direto - com autenticação:
#curl -u alfecjo:acfa -X GET http://host.docker.internal:8081/api/health